
public class ChangePhoneForm extends javax.swing.JFrame {

    /**
     * Creates new form ChangeTel
     */
    public ChangePhoneForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_ChangePhone = new javax.swing.JLabel();
        lbl_Phone = new javax.swing.JLabel();
        btn_Cancel = new javax.swing.JButton();
        btn_Ok = new javax.swing.JButton();
        txt_NamePhone = new javax.swing.JTextField();
        lbl_bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(546, 293));
        setResizable(false);
        setSize(new java.awt.Dimension(546, 293));
        getContentPane().setLayout(null);

        lbl_ChangePhone.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbl_ChangePhone.setText("Change Phone");
        getContentPane().add(lbl_ChangePhone);
        lbl_ChangePhone.setBounds(190, 50, 190, 50);

        lbl_Phone.setText("New Phone :");
        getContentPane().add(lbl_Phone);
        lbl_Phone.setBounds(140, 130, 80, 16);

        btn_Cancel.setBackground(new java.awt.Color(255, 0, 0));
        btn_Cancel.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_Cancel.setForeground(new java.awt.Color(255, 255, 255));
        btn_Cancel.setText("Cancel");
        btn_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Cancel);
        btn_Cancel.setBounds(360, 170, 80, 25);

        btn_Ok.setBackground(new java.awt.Color(34, 167, 240));
        btn_Ok.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_Ok.setForeground(new java.awt.Color(255, 255, 255));
        btn_Ok.setText("OK");
        btn_Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OkActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Ok);
        btn_Ok.setBounds(290, 170, 60, 25);

        txt_NamePhone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_NamePhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NamePhoneActionPerformed(evt);
            }
        });
        getContentPane().add(txt_NamePhone);
        txt_NamePhone.setBounds(220, 120, 220, 30);

        lbl_bg.setForeground(new java.awt.Color(255, 255, 255));
        lbl_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bgProfileChange.jpg"))); // NOI18N
        getContentPane().add(lbl_bg);
        lbl_bg.setBounds(0, 0, 550, 300);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_NamePhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NamePhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NamePhoneActionPerformed

    private void btn_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelActionPerformed
        // TODO add your handling code here:
        ProfileService.showProfileForm();
        this.hide();
    }//GEN-LAST:event_btn_CancelActionPerformed

    private void btn_OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OkActionPerformed
        // TODO add your handling code here:
        User user = ProfileService.getUser("user2");
        String phone = txt_NamePhone.getText();
        if(ProfileService.checkNull(phone)&&ProfileService.checkLengthPhone(phone)&&ProfileService.checkFristNumber(phone)){
            ProfileService.changePhone(user,phone);
            ProfileService.showProfileForm();
            this.hide();
        }else{
            txt_NamePhone.setText("");
        }
    }//GEN-LAST:event_btn_OkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePhoneForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePhoneForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePhoneForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePhoneForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePhoneForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cancel;
    private javax.swing.JButton btn_Ok;
    private javax.swing.JLabel lbl_ChangePhone;
    private javax.swing.JLabel lbl_Phone;
    private javax.swing.JLabel lbl_bg;
    private javax.swing.JTextField txt_NamePhone;
    // End of variables declaration//GEN-END:variables
}
