import java.util.*;
import javax.swing.JLabel;
public class ProfileForm extends javax.swing.JFrame {

    /**
     * Creates new form ProfileService
     */
    public ProfileForm() {
        initComponents();
        User user = ProfileService.getUser("user2");
        lbl_Username.setText(user.getUsername());
        lbl_Address.setText(user.getAddress());
        lbl_Phone.setText(user.getPhone());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_Upload = new javax.swing.JButton();
        btn_ChangeAddress = new javax.swing.JButton();
        btn_ChangePhone = new javax.swing.JButton();
        btn_Back = new javax.swing.JButton();
        lbl_Profile = new javax.swing.JLabel();
        btn_Payment = new javax.swing.JButton();
        lbl_Imgprofile = new javax.swing.JLabel();
        lbl_phone = new javax.swing.JLabel();
        lbl_address = new javax.swing.JLabel();
        lbl_username = new javax.swing.JLabel();
        lbl_Phone = new javax.swing.JLabel();
        lbl_Address = new javax.swing.JLabel();
        lbl_Username = new javax.swing.JLabel();
        lbl_bgprofile = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(840, 580));
        setMinimumSize(new java.awt.Dimension(840, 580));
        setPreferredSize(new java.awt.Dimension(840, 580));
        setResizable(false);
        setSize(new java.awt.Dimension(850, 585));
        getContentPane().setLayout(null);

        btn_Upload.setBackground(new java.awt.Color(255, 0, 0));
        btn_Upload.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_Upload.setForeground(new java.awt.Color(255, 255, 255));
        btn_Upload.setText("Upload");
        btn_Upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UploadActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Upload);
        btn_Upload.setBounds(680, 180, 90, 30);

        btn_ChangeAddress.setBackground(new java.awt.Color(255, 0, 0));
        btn_ChangeAddress.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_ChangeAddress.setForeground(new java.awt.Color(255, 255, 255));
        btn_ChangeAddress.setText("Change Address");
        btn_ChangeAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ChangeAddressActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ChangeAddress);
        btn_ChangeAddress.setBounds(650, 300, 140, 40);

        btn_ChangePhone.setBackground(new java.awt.Color(255, 0, 0));
        btn_ChangePhone.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_ChangePhone.setForeground(new java.awt.Color(255, 255, 255));
        btn_ChangePhone.setText("Change Phone");
        btn_ChangePhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ChangePhoneActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ChangePhone);
        btn_ChangePhone.setBounds(650, 350, 140, 40);

        btn_Back.setBackground(new java.awt.Color(255, 0, 0));
        btn_Back.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_Back.setForeground(new java.awt.Color(255, 255, 255));
        btn_Back.setText("Back");
        btn_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Back);
        btn_Back.setBounds(30, 490, 100, 30);

        lbl_Profile.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lbl_Profile.setText("Profile");
        getContentPane().add(lbl_Profile);
        lbl_Profile.setBounds(40, 30, 119, 44);

        btn_Payment.setBackground(new java.awt.Color(34, 167, 240));
        btn_Payment.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_Payment.setForeground(new java.awt.Color(255, 255, 255));
        btn_Payment.setText("Order");
        btn_Payment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PaymentActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Payment);
        btn_Payment.setBounds(510, 40, 100, 30);

        lbl_Imgprofile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Man.png"))); // NOI18N
        lbl_Imgprofile.setMaximumSize(new java.awt.Dimension(550, 300));
        lbl_Imgprofile.setMinimumSize(new java.awt.Dimension(550, 300));
        getContentPane().add(lbl_Imgprofile);
        lbl_Imgprofile.setBounds(650, 20, 150, 160);

        lbl_phone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_phone.setText("Phone :");
        getContentPane().add(lbl_phone);
        lbl_phone.setBounds(100, 370, 90, 22);

        lbl_address.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_address.setText("Address :");
        getContentPane().add(lbl_address);
        lbl_address.setBounds(100, 320, 110, 22);

        lbl_username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_username.setText("Username :");
        getContentPane().add(lbl_username);
        lbl_username.setBounds(100, 270, 110, 22);

        lbl_Phone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_Phone.setText("...");
        getContentPane().add(lbl_Phone);
        lbl_Phone.setBounds(240, 360, 390, 40);

        lbl_Address.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_Address.setText("...");
        getContentPane().add(lbl_Address);
        lbl_Address.setBounds(240, 310, 390, 40);

        lbl_Username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_Username.setText("...");
        getContentPane().add(lbl_Username);
        lbl_Username.setBounds(240, 260, 390, 40);

        lbl_bgprofile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bgProfile.jpg"))); // NOI18N
        lbl_bgprofile.setMaximumSize(new java.awt.Dimension(840, 580));
        lbl_bgprofile.setMinimumSize(new java.awt.Dimension(840, 580));
        lbl_bgprofile.setPreferredSize(new java.awt.Dimension(840, 580));
        getContentPane().add(lbl_bgprofile);
        lbl_bgprofile.setBounds(-10, 0, 860, 580);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_UploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UploadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_UploadActionPerformed

    private void btn_ChangePhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ChangePhoneActionPerformed
        // TODO add your handling code here:
        ProfileService.showChangePhoneForm();
        this.hide();
    }//GEN-LAST:event_btn_ChangePhoneActionPerformed

    private void btn_ChangeAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ChangeAddressActionPerformed
        // TODO add your handling code here:
        ProfileService.showChangeAddressForm();
        this.hide();
         
        
    }//GEN-LAST:event_btn_ChangeAddressActionPerformed

    private void btn_PaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_PaymentActionPerformed

    private void btn_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackActionPerformed
        // TODO add your handling code here:
        ProfileService.showMainpageForm();
        this.hide();
    }//GEN-LAST:event_btn_BackActionPerformed

    public static void main(String args[]) {
       
           
                
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfileForm().setVisible(true); 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Back;
    private javax.swing.JButton btn_ChangeAddress;
    private javax.swing.JButton btn_ChangePhone;
    private javax.swing.JButton btn_Payment;
    private javax.swing.JButton btn_Upload;
    private javax.swing.JLabel lbl_Address;
    private javax.swing.JLabel lbl_Imgprofile;
    private javax.swing.JLabel lbl_Phone;
    private javax.swing.JLabel lbl_Profile;
    private javax.swing.JLabel lbl_Username;
    private javax.swing.JLabel lbl_address;
    private javax.swing.JLabel lbl_bgprofile;
    private javax.swing.JLabel lbl_phone;
    private javax.swing.JLabel lbl_username;
    // End of variables declaration//GEN-END:variables

    
}
